Repository Ctoic/Lisbook, pull requests merged in 2024-10, with the labels that each got.

#14 Added Card and Animations
  index.html
Labels: hactoberfest, hactoberfest-accepted

#15 added dynamic contributors section at bottom of readme
  README.md
Labels: hactoberfest

#18 [#8] Home page mobile menu navigation added
  index.html
Labels: hactoberfest-accepted

#20 Play/Pause Animation added
  app.js
  index.html
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#21 Adding Contributors to README.md dynamically [#9]
  .github/workflows/contributors.yml
  README.md
Labels: hacktoberfest

#28 Consolidation of CSS and JavaScript files for improved maintenance
  fs.html
  index.html
  pbd.html
  rdpd.html
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#24 Update README.md
  README.md
Labels: hacktoberfest

#41 Improved theme management and updated interface
  fs.html
  index.html
  pbd.html
  rdpd.html
  script.js
  style.css
Labels: hacktoberfest-accepted

#43 I added the descriptions for the books along with the associated cover
  Images/Frankestine.jpg
  Images/Sapiens.jpg
  Images/TheCatcher.jpg
  fs.html
  pbd.html
  rdpd.html
Labels: hacktoberfest

#45 feat: Add keyboard shortcuts for audio control
  script.js
  style.css
Labels: hacktoberfest-accepted

#46 Added Tooltips on hover. Added action button color change on hover.
  data/books.json
  index.html
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#59 Fixed the issue - All the contributors are not visible On readme. #53
  .github/workflows/main.yml
  README.md
Labels: hacktoberfest-accepted

#61 Pull Request: Add "About" Page to LisBook Project
  Images/lisbook-about.jpg
  Images/lisbook-logo.png
  about.html
  fs.html
  index.html
  pbd.html
  rdpd.html
  script.js
  style.css
Labels: hacktoberfest-accepted

#82 Redesign Footer Section
  about.html
  adventures.html
  app.js
  faq.html
  fs.html
  index.html
  pages/header.html
  pbd.html
  rdpd.html
  script.js
  test.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#105 added social media links
  pages/footer.html
Labels: hacktoberfest, hacktoberfest-accepted

#107 theme is stable throughout the pages #104 (Fixes for Issue #104)
  faq.html
  script.js
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#115 Added functionality for increasing and decreasing the playback speed
  adventures.html
  app.js
  fs.html
  index.html
  pbd.html
  rdpd.html
  script.js
  test.html
Labels: hacktoberfest, hacktoberfest-accepted

#127 new feature - profile section
  about.html
  contact.html
  faq.html
  index.html
  pages/footer.html
  profile.html
  script.js
  style.css
Labels: hacktoberfest-accepted
