Repository Ctoic/Lisbook, pull requests merged in 2025-10, with the labels that each got.

#204 fix: explore books button redirect fixed
  index.html
Labels: hactoberfest, hacktoberfest, hacktoberfest-accepted

#209 Feat: Show contributors dynamically
  about.html
  script.js
Labels: hactoberfest, hactoberfest-accepted, hacktoberfest, hacktoberfest-accepted

#232 Added ai chatbot
  index.html
  marked.min.js
  script.js
  style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted, Lisbook, javascript

#248 Enhancement/content and discovery
  explore.html
  explore.js
  explore_style.css
Labels: good first issue, hactoberfest, hactoberfest-accepted, hacktoberfest, hacktoberfest-accepted

#247 Fix JS errors in app.js, explore.js, share.js for homepage (Issue #212)
  index.html
Labels: bug, enhancement, hacktoberfest, hacktoberfest-accepted, pull-latest-code
